-- Run in the Supabase SQL Editor for a new project.
create table public.categories (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_np text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id),
  name_en text not null,
  name_np text,
  description text,
  unit text not null default 'kg' check (unit in ('kg', 'piece', 'pack')),
  price_per_unit numeric(10,2) not null check (price_per_unit >= 0),
  image_url text,
  is_halal boolean not null default true,
  in_stock boolean not null default true,
  is_visible boolean not null default true,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.customers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null unique,
  email text,
  address text,
  postal_code text,
  city text,
  created_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  source text not null default 'online' check (source in ('online','pos')),
  customer_id bigint references public.customers(id),
  fulfillment text not null default 'pickup' check (fulfillment in ('pickup','delivery')),
  status text not null default 'pending' check (status in ('pending','confirmed','ready','completed','cancelled')),
  payment_method text check (payment_method in ('cash','card','mobilepay','online')),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid','paid','refunded')),
  subtotal numeric(10,2) not null default 0,
  delivery_fee numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  requested_time timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null,
  quantity numeric(10,3) not null check (quantity > 0),
  unit text not null check (unit in ('kg','piece','pack')),
  unit_price numeric(10,2) not null,
  line_total numeric(10,2) not null
);

create or replace function public.is_admin()
returns boolean
language sql stable
as $$ select coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false) $$;

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Categories are public" on public.categories for select to anon, authenticated using (true);
create policy "Admins manage categories" on public.categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Visible products are public" on public.products for select to anon, authenticated using (is_visible and in_stock or public.is_admin());
create policy "Admins manage products" on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins read customers" on public.customers for select to authenticated using (public.is_admin());
create policy "Admins read orders" on public.orders for select to authenticated using (public.is_admin());
create policy "Admins manage orders" on public.orders for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins read order items" on public.order_items for select to authenticated using (public.is_admin());

create or replace function public.create_order(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  customer jsonb := coalesce(payload -> 'customer', '{}'::jsonb);
  order_id bigint;
  customer_id bigint;
  order_ref text;
  subtotal numeric(10,2) := 0;
  delivery_fee numeric(10,2) := 0;
  line jsonb;
  product public.products%rowtype;
  quantity numeric(10,3);
  line_total numeric(10,2);
begin
  if auth.uid() is null then
    raise exception 'Sign in is required to place an order';
  end if;
  if coalesce(jsonb_typeof(payload -> 'items'), '') <> 'array' or coalesce(jsonb_array_length(payload -> 'items'), 0) = 0 then
    raise exception 'Order must include at least one item';
  end if;
  if coalesce(customer ->> 'full_name', '') = '' or coalesce(customer ->> 'phone', '') = '' then
    raise exception 'Customer name and phone are required';
  end if;
  if coalesce(payload ->> 'fulfillment', 'pickup') not in ('pickup','delivery') then
    raise exception 'Invalid fulfillment method';
  end if;

  insert into public.customers(full_name, phone, email, address, postal_code, city)
  values (customer ->> 'full_name', customer ->> 'phone', nullif(customer ->> 'email',''), nullif(customer ->> 'address',''), nullif(customer ->> 'postal_code',''), nullif(customer ->> 'city',''))
  on conflict (phone) do update set full_name = excluded.full_name, email = excluded.email, address = excluded.address, postal_code = excluded.postal_code, city = excluded.city
  returning id into customer_id;

  for line in select value from jsonb_array_elements(payload -> 'items') loop
    select * into product from public.products where id = (line ->> 'product_id')::bigint and is_visible and in_stock;
    if not found then raise exception 'A product is unavailable'; end if;
    quantity := (line ->> 'quantity')::numeric;
    if quantity <= 0 or quantity > 1000 then raise exception 'Invalid item quantity'; end if;
    line_total := round(quantity * product.price_per_unit, 2);
    subtotal := subtotal + line_total;
  end loop;

  if payload ->> 'fulfillment' = 'delivery' then delivery_fee := 39; end if;
  if lower(coalesce(payload ->> 'campaign','')) = 'dashain' then
    order_ref := 'DASH-' || upper(left(regexp_replace(customer ->> 'full_name', '[^A-Za-z0-9]', '', 'g'), 3)) || '-' || upper(substr(md5(gen_random_uuid()::text), 1, 6));
  else
    order_ref := 'EB-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substr(md5(gen_random_uuid()::text), 1, 6));
  end if;

  insert into public.orders(order_number, customer_id, fulfillment, payment_method, subtotal, delivery_fee, total, requested_time, notes)
  values (order_ref, customer_id, coalesce(payload ->> 'fulfillment','pickup'), nullif(payload ->> 'payment_method',''), subtotal, delivery_fee, subtotal + delivery_fee, nullif(payload ->> 'requested_time','')::timestamptz, nullif(payload ->> 'notes',''))
  returning id into order_id;

  for line in select value from jsonb_array_elements(payload -> 'items') loop
    select * into product from public.products where id = (line ->> 'product_id')::bigint;
    quantity := (line ->> 'quantity')::numeric;
    line_total := round(quantity * product.price_per_unit, 2);
    insert into public.order_items(order_id, product_id, product_name, quantity, unit, unit_price, line_total)
    values (order_id, product.id, product.name_en, quantity, product.unit, product.price_per_unit, line_total);
  end loop;

  return jsonb_build_object('id', order_id, 'order_number', order_ref, 'subtotal', subtotal, 'delivery_fee', delivery_fee, 'total', subtotal + delivery_fee);
end;
$$;

revoke all on function public.create_order(jsonb) from public, anon;
grant execute on function public.create_order(jsonb) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do nothing;

create policy "Product images are public" on storage.objects for select using (bucket_id = 'product-images');
create policy "Admins upload product images" on storage.objects for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());
create policy "Admins update product images" on storage.objects for update to authenticated using (bucket_id = 'product-images' and public.is_admin()) with check (bucket_id = 'product-images' and public.is_admin());
create policy "Admins delete product images" on storage.objects for delete to authenticated using (bucket_id = 'product-images' and public.is_admin());

insert into public.categories (name_en, name_np, sort_order) values
  ('Goat','खसी',1),('Buffalo','भैंसी',2),('Chicken','कुखुरा',3),('Fish','माछा',4),('Spices & Pantry','मसला',5),('Ready to Cook','तयारी',6);

insert into public.products (category_id, name_en, name_np, description, unit, price_per_unit, is_featured)
select c.id, p.name_en, p.name_np, p.description, p.unit, p.price, p.featured
from (values
 ('Goat','Goat Curry Cut (Bone-in)','खसीको मासु','Fresh bone-in goat, cut for curry.','kg',149.00,true),
 ('Goat','Goat Boti (Boneless)','बोटी','Boneless goat cubes.','kg',179.00,false),
 ('Goat','Goat Liver & Offal','खसीको भुँडी','Mixed goat offal, cleaned.','kg',89.00,false),
 ('Buffalo','Buffalo Curry Cut','भैंसीको मासु','Fresh buffalo, bone-in, curry cut.','kg',89.00,true),
 ('Buffalo','Buffalo Mince','किमा','Freshly minced buffalo.','kg',95.00,false),
 ('Chicken','Whole Chicken','कुखुराको मासु','Whole chicken, cleaned, skin-on.','kg',45.00,true),
 ('Chicken','Chicken Curry Cut',null,'Cut into curry pieces, bone-in.','kg',49.00,false),
 ('Spices & Pantry','Timur (Sichuan Pepper)','टिमुर','Whole Nepali timur, 100g pack.','pack',35.00,false),
 ('Ready to Cook','Marinated Sekuwa Skewers','सेकुवा','Ready-to-grill goat sekuwa, marinated in-house.','pack',65.00,true)
) as p(category, name_en, name_np, description, unit, price, featured)
join public.categories c on c.name_en = p.category;
